<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "multifield_validation"
 *
 * Auto generated by Extension Builder 2021-05-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 't3-template',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Marcel Arndt',
    'author_email' => 'dim@eml.cc',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.0.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
